name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      # aquí irían tus builds/tests

 # super_linter:             # usa minúsculas y sin espacios por convención
  #  runs-on: ubuntu-latest
   # needs: [build]
    #steps:
     # - name: Checkout code
      #  uses: actions/checkout@v4

      #- name: Run Super-Linter
       # uses: super-linter/super-linter@v6
        #env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # requerido
          #DEFAULT_BRANCH: main                       # recomendado
          # VALIDATE_ALL_CODEBASE: true             # opcional (true=todo el repo)
          # FILTER_REGEX_INCLUDE: (^|/)src/         # opcional
          # LINTER_RULES_PATH: config/lint          # opcional

  deploy_app:
    environment: Production
    runs-on: [self-hosted, Linux, X64, vm-control, ansible]

    steps:
      - name: Checkout repo de infraestructura
        uses: actions/checkout@v4
        with:
          repository: MisaelVa06/DevOpslvl2
          ref: main
          path: other

    # (Opcional) instalar Ansible si tu runner no lo tiene
    # - run: sudo apt-get update -y && sudo apt-get install -y ansible

      - name: Preparar vault pass file
        env:
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
        run: |
          umask 177
          echo -n "$VAULT_PASSWORD" > /home/gha/.vault_prod
  
      - name: Deploy (vault vía FILE con ID 'prod')
        working-directory: other
        run: |
          ansible-playbook -i hosts.ini deploy_production.yml \
            --vault-id prod@file:/home/gha/.vault_prod
          # Alternativa clásica:
          # ansible-playbook -i hosts.ini deploy_production.yml \
          #   --vault-password-file /home/gha/.vault_prod
  
    
          

 


