name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, vm-control]  # usa tus labels reales
    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"  # caching integrado (requiere requirements*.txt)

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest flake8

      - name: Lint
        run: flake8 .
        # Si solo quieres warning y que no bloquee:
        # run: flake8 . || echo "flake8 warnings (no bloquea)"

      - name: Tests
        run: |
          set -e
          pytest -q || rc=$?
          # Si no hay tests, pytest devuelve 5. Lo tratamos como éxito.
          if [ "${rc:-0}" -eq 5 ]; then
            echo "No tests collected. Marking as success."
            exit 0
          elif [ -n "${rc}" ]; then
            exit "${rc}"
          fi

